[MNTR-7] Configure CI to handle automatic deploy to Heroku
pwdypb/Mentoring pull request #17
Opened 2017-08-15 20:41 UTC by sajti12

Resolves #7

2017-08-15 20:56 UTC, sajti12 commented
Please note that from now on two environment variables are required to be set in CircleCI:
- `HEROKU_API_KEY`: required by Heroku for authentication
- `HEROKU_APP_NAME`: supplied to deploy command

2017-08-16 08:22 UTC, pwdypb requested changes

2017-08-16 08:22 UTC, pwdypb commented on .circleci/config.yml
> +           destination: mentoring-0.0.1-SNAPSHOT.war
Should use `$WAR_FILE_NAME` variable

2017-08-16 08:22 UTC, pwdypb commented on .circleci/config.yml
> +              - mentoring-0.0.1-SNAPSHOT.war
Same here

2017-08-16 08:25 UTC, pwdypb commented
The app will be available on: https://trexxx.herokuapp.com/

2017-08-16 08:25 UTC, sajti12 commented on .circleci/config.yml
> +           destination: mentoring-0.0.1-SNAPSHOT.war
It isn't supported at the moment.

2017-08-16 08:25 UTC, sajti12 commented on .circleci/config.yml
> +              - mentoring-0.0.1-SNAPSHOT.war
See above

2017-08-16 08:40 UTC, pwdypb approved these changes

2017-08-17 11:55 UTC, merged