[MNTR-1] Init repo
pwdypb/Mentoring pull request #9
Opened 2017-07-17 21:44 UTC by sajti12

#1

2017-07-18 12:12 UTC, pwdypb requested changes
Add some unit tests (even if it's just an assertTrue(true))

2017-07-19 16:21 UTC, sajti12 commented
@pwdypb Please specify the purpose for writing unit tests in this case (e.g. tweaking CI process), otherwise there is no point in providing tests at this point.

2017-07-19 17:01 UTC, pwdypb commented
That's exactly it, wanted to have tests so I can setup CI. Since then I realized that no actual tests needed for "mvn test" to be successful though.

2017-07-19 17:01 UTC, pwdypb approved these changes

2017-07-21 16:19 UTC, merged